Table dim_sellers {
    id integer [primary key]
    seller_id varchar
    seller_zip_code_prefix int
    seller_city varchar
    seller_state varchar
  }
  
  Table dim_product {
    id integer [primary key]
    product_id varchar
    product_category_name varchar
    product_name_lenght varchar
    product_description_lenght varchar
    product_photos_qty varchar
    product_weight_g varchar
    product_length_cm varchar
    product_height_cm varchar
    product_width_cm varchar
  }
  
  Table dim_customer {
    customer_unique_id varchar [primary key]
    customer_id varchar
    customer_zip_code_prefix int
    customer_city varchar
    customer_state varchar
  }
  
  Table fact_orders {
    order_id varchar
    customer_id varchar
    order_status varchar
    order_purchase_timestamp timestamp
    order_approved_at timestamp
    order_delivered_carrier_date timestamp
    order_delivered_customer_date timestamp
    order_estimated_delivery_date timestamp
    order_item_id varchar
    product_id varchar
    seller_id varchar
    shipping_limit_date timestamp
    price float
    freight_value float
    
  }
  
  Ref: dim_customer.customer_id < fact_orders.customer_id // many-to-one
  
  Ref: dim_product.product_id < fact_orders.product_id
  
  Ref: dim_sellers.seller_id < fact_orders.seller_id